### ISSUE TITLE
FireFox shows time spent on the page

### ISSUE THREAD

**Issue by PeterDeKeer** [kaaes/timing#1]
See FireFox issue (if it's a FireFox issue) maybe it's an issue with this script
https://bugzilla.mozilla.org/show_bug.cgi?id=748276

Also see recent twitter conversation
https://twitter.com/#!/kaaes/status/198348620339228672

**Comment by kaaes** [comment]
Hi,

Thanks for filing this. I looked into the code and it indeed seems like a FF bug. When you refresh the page the value of performance.timing.navigationStart is not related to the actual actions on the page. It's also not equal to the performance.timing.loadEventEnd of the previous page. And it doesn't happen in Chrome.

Results in Aurora's web console https://skitch.com/kaaes/83aq6/dock

**Comment by PeterDeKeer** [comment]
Thanks! I added your info to the bugreport. Hope someone picks this up...
https://bugzilla.mozilla.org/show_bug.cgi?id=748276
