### ISSUE TITLE
Bookmark won't work because of MIME type

### ISSUE THREAD

**Issue by fedevegili** [kaaes/timing#5]
Hello, everytime I try to load the bookmark, the follow message appears on the console:

Resource interpreted as Script but transferred with MIME type text/plain: "https://raw.githubusercontent.com/kaaes/timing/gh-pages/profiler.js". VM25765:1

Refused to execute script from 'https://raw.github.com/kaaes/timing/gh-pages/profiler.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. defaultframe_opener.php?oid=menu,1200231,73,-1,-1:1

Uncaught ReferenceError: __Profiler is not defined.

Probably your host changed the default mime type.

**Comment by infernalmaster** [comment]
You need change link in bookmark to script from https://raw.githubusercontent.com/kaaes/timing/gh-pages/profiler.js to [//kaaes.github.io/timing/profiler.js](//kaaes.github.io/timing/profiler.js)
